#!/usr/bin/env python3

import sys

rtc_list = ['ds1307', 'ds3231', 'pcf8523']

print('This script will update RPI settings for RTC support\n')
print('Please select RTC chip number and press ENTER. Press 4 for Exit without changes. \n')
user_choice = input('1: ' + rtc_list[0] + '\n2: ' + rtc_list[1] + '\n3: ' + rtc_list[2] + '\n4: EXIT \n')

try:
   val = int(user_choice)
   if( val == 1 or val == 2 or val == 3 ):
       print("Configuration for RTC:  " + rtc_list[val - 1] )
   else:
       print("EXIT ")
       sys.exit()      
       
except ValueError:
   print("Wrong choice")

rtc_to_set = str(rtc_list[int(user_choice) - 1])
   
try:
  fileConfig = open('/boot/config.txt', 'r')
  content = fileConfig.readlines()
  fileConfig.close()
  
  founded = False
  
  text = 'dtoverlay=i2c-rtc,'
  
  for i in range(len(content)):
      if text in content[i]:
          content[i] = text + rtc_to_set + '\n'
          founded = True
          break
  
  if not founded:
      content.append('\n' + text + rtc_to_set)
  
  with open('/boot/config.txt', 'w') as file:
      file.writelines(content)
  print('File config.txt has been changed with new RTC ' + rtc_to_set + ' entry')
  print('Saving config.txt')
  file.close()
except Exception:
  print('Error. Cannot change config.txt. Try sudo or add RTC support manually.')
  
try:
  fileConfig = open('/etc/modules', 'r')
  content = fileConfig.readlines()
  fileConfig.close()
  
  founded = False
  
  for i in range(len(content)):
      if 'rtc-' in content[i]:
          content[i] = 'rtc-' + rtc_to_set + '\n'
          founded = True
          break
  
  if not founded:
      content.append('\n' + 'rtc-' + rtc_to_set)
  
  with open('/etc/modules', 'w') as file:
      file.writelines(content)
  print ('Saving new entry for ' + rtc_to_set + ' in modules.')
  file.close()
except Exception:
  print('Error. Cannot change /etc/modules. Activate RTC manually.')
  
try:
  fileConfig = open('/lib/udev/hwclock-set', 'r')
  content = fileConfig.readlines()
  fileConfig.close()
  
  founded = False
  
  for i in range(len(content)):
      if 'if [ -e /run/systemd/system ] ; then' in content[i]:
          content[i] = "#if [ -e /run/systemd/system ] ; then\n"
          content[i + 1] = "#exit 0\n"
          content[i + 2] = "#fi\n"
          founded = True
          break
       
  with open('/lib/udev/hwclock-set', 'w') as file:
      file.writelines(content)
  print ('Saving udev file')
  file.close()
except Exception:
  print('Error. Cannot change /lib/udev/hwclock-set. Activate RTC manually.')
  
print('RTC setting added successfully.')

